name: Continuous Integration

on:
  push:
    branches:
      - master


jobs:
  builds-and-push:
    runs-on: windows
    steps:
      - name: Setup Maven and Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests
        run: mvn clean test

      - name: Build project
        run: mvn clean package

      - name: Build image artifact
        env:

        run:
          mvn spring-boot:build-image
          docker push